#!/usr/bin/env bash
#Creates file in /var/run/myscript.pid containing its PID.

handle_sigterm_sigquit() {
  echo "I hate the kill command"
  cleanup_and_exit
}

handle_sigint() {
  echo "Y U no love me?!"
}

cleanup_and_exit() {
  echo "Cleaning up and exiting..."
  rm -f /var/run/myscript.pid
  exit 0
}

trap 'handle_sigterm_sigquit' SIGTERM SIGQUIT
trap 'handle_sigint' SIGINT

echo $$ > /var/run/myscript.pid

while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done
